#cloud-config
local-hostname: ${var.VM_Name}-${count.index + 1}
instance-id: ${var.VM_Name}-${count.index + 1}
network:
  version: 2
  ethernets:
    ens192:
      dhcp4: false
      addresses:
        - ${var.private_IP[count.index + 1]}/24
      gateway4: ${var.gateway_IP[count.index + 1]}
      nameservers:
        addresses: ${var.dns_server}
growpart:
  mode: auto
  devices: ['/dev/sda2']
  ignore_growroot_disabled: true
wait-on-network:
  ipv4: true
